### PR TITLE
Data-collector: Added request validation logging for when validation fails

### LINKED ISSUE #39: [FEAT] Request validation logging
**Is your feature request related to a problem? Please describe.**
*As a* Security Engineer
*I want* to be alerted if data-collector requests are failing validation
*So that* I can investigate the issue and minimise how much data is lost

**Describe the solution you'd like**
I'd like for all requests that fail validation to be logged with the request body, metadata about the request, diagnostic information and the reason the validation failed, so that failing requests can be investigated.

**Additional context**
I think that logging to stdout in a lambda results in those log lines being captured in CloudWatch. Users can then forward these logs to their log aggregator of choice.

### PR DESCRIPTION
**Pull request by DanHatesNumbers**
# What does this PR change?
- Adds logging at WARN level for requests that fail validation with a message containing the reason validation failed and the request body that failed validation.

# Why is it important?
- Closes #39 

# Checklist
- [x] Tests added/updated as appropriate
- [x] Documentation added/updated as appropriate

If this PR introduces a new tool:
- [ ] Documentation on how to handle false positives added
- [ ] Documentation on how to configure the tool added

### CODE REVIEW

**Comment by DanHatesNumbers** [comment]
@ed-woodfall @DM-sb I'm not sure about the formatting of the log output. Any suggestions for improvements or additional information that would be useful would be great!

**Comment by DanHatesNumbers** [comment]
An example of what the logging output looks like as this PR currently stands:

```
Attaching to kiln_data-collector_1
data-collector_1  | [2019-10-23T14:47:26Z INFO  actix_server::builder] Starting 6 workers
data-collector_1  | [2019-10-23T14:47:26Z INFO  actix_server::builder] Starting server on 0.0.0.0:8080
data-collector_1  | [2019-10-23T14:47:31Z WARN  data_collector] Request did not pass validation because: Application name required.
data-collector_1  |     Request body: {
data-collector_1  |
data-collector_1  |         "git_branch": "master",
data-collector_1  |         "git_commit_hash": "e99f715d0fe787cd43de967b8a79b56960fed3e5",
data-collector_1  |         "tool_name": "example tool",
data-collector_1  |         "tool_output": "{}",
data-collector_1  |         "output_format": "JSON",
data-collector_1  |         "start_time": "2019-09-13T19:35:38+00:00",
data-collector_1  |         "end_time": "2019-09-13T19:37:14+00:00",
data-collector_1  |         "environment": "Local",
data-collector_1  |         "tool_version": "1.0"
data-collector_1  |     }
data-collector_1  |
data-collector_1  | [2019-10-23T14:47:31Z INFO  actix_web::middleware::logger] 172.20.0.1:37694 PostmanRuntime/7.18.0
data-collector_1  | [2019-10-23T14:47:31Z INFO  actix_web::middleware::logger] 172.20.0.1:37694 "POST / HTTP/1.1" 400 62 "-" "PostmanRuntime/7.18.0" 0.000082
data-collector_1  | [2019-10-23T14:48:19Z INFO  actix_web::middleware::logger] 172.20.0.1:37696 PostmanRuntime/7.18.0
data-collector_1  | [2019-10-23T14:48:19Z INFO  actix_web::middleware::logger] 172.20.0.1:37696 "POST / HTTP/1.1" 200 0 "-" "PostmanRuntime/7.18.0" 0.003363
data-collector_1  | [2019-10-23T14:48:20Z INFO  actix_web::middleware::logger] 172.20.0.1:37696 PostmanRuntime/7.18.0
data-collector_1  | [2019-10-23T14:48:20Z INFO  actix_web::middleware::logger] 172.20.0.1:37696 "POST / HTTP/1.1" 200 0 "-" "PostmanRuntime/7.18.0" 0.002570
data-collector_1  | [2019-10-23T14:48:26Z WARN  data_collector] Request did not pass validation because: Application name present but empty.
data-collector_1  |     Request body: {
data-collector_1  |         "application_name": "",
data-collector_1  |         "git_branch": "master",
data-collector_1  |         "git_commit_hash": "e99f715d0fe787cd43de967b8a79b56960fed3e5",
data-collector_1  |         "tool_name": "example tool",
data-collector_1  |         "tool_output": "{}",
data-collector_1  |         "output_format": "JSON",
data-collector_1  |         "start_time": "2019-09-13T19:35:38+00:00",
data-collector_1  |         "end_time": "2019-09-13T19:37:14+00:00",
data-collector_1  |         "environment": "Local",
data-collector_1  |         "tool_version": "1.0"
data-collector_1  |     }
data-collector_1  |
data-collector_1  | [2019-10-23T14:48:26Z INFO  actix_web::middleware::logger] 172.20.0.1:37698 PostmanRuntime/7.18.0
data-collector_1  | [2019-10-23T14:48:26Z INFO  actix_web::middleware::logger] 172.20.0.1:37698 "POST / HTTP/1.1" 400 71 "-" "PostmanRuntime/7.18.0" 0.000586
data-collector_1  | [2019-10-23T14:48:37Z INFO  actix_web::middleware::logger] 172.20.0.1:37700 PostmanRuntime/7.18.0
data-collector_1  | [2019-10-23T14:48:37Z INFO  actix_web::middleware::logger] 172.20.0.1:37700 "POST / HTTP/1.1" 200 0 "-" "PostmanRuntime/7.18.0" 0.002844
```

**Comment by DM-sb** [comment]
Looks fine to me. Maybe where there is a missing JSON name value pair, we could print the actual name, e.g. "`application_name` missing from request"

**Comment by DanHatesNumbers** [comment]
Ah, so use the JSON field name instead of the plain one?

**Comment by DanHatesNumbers** [comment]
Updated logging sample:

```
data-collector_1  | [2019-10-28T12:43:33Z INFO  actix_server::builder] Starting 6 workers
data-collector_1  | [2019-10-28T12:43:33Z INFO  actix_server::builder] Starting server on 0.0.0.0:8080
data-collector_1  | [2019-10-28T12:43:43Z INFO  actix_web::middleware::logger] 172.20.0.1:39036 PostmanRuntime/7.18.0
data-collector_1  | [2019-10-28T12:43:43Z INFO  actix_web::middleware::logger] 172.20.0.1:39036 "POST / HTTP/1.1" 200
0 "-" "PostmanRuntime/7.18.0" 0.063375
data-collector_1  | [2019-10-28T12:43:49Z WARN  data_collector] Request did not pass validation. Error message: Applic
ation name required. JSON field name: application_name. Request body: {
data-collector_1  |
data-collector_1  |         "git_branch": "master",
data-collector_1  |         "git_commit_hash": "e99f715d0fe787cd43de967b8a79b56960fed3e5",
data-collector_1  |         "tool_name": "example tool",
data-collector_1  |         "tool_output": "{}",
data-collector_1  |         "output_format": "JSON",
data-collector_1  |         "start_time": "2019-09-13T19:35:38+00:00",
data-collector_1  |         "end_time": "2019-09-13T19:37:14+00:00",
data-collector_1  |         "environment": "Local",
data-collector_1  |         "tool_version": "1.0"
data-collector_1  |     }
data-collector_1  |
data-collector_1  | [2019-10-28T12:43:49Z INFO  actix_web::middleware::logger] 172.20.0.1:39038 PostmanRuntime/7.18.0
data-collector_1  | [2019-10-28T12:43:49Z INFO  actix_web::middleware::logger] 172.20.0.1:39038 "POST / HTTP/1.1" 400
99 "-" "PostmanRuntime/7.18.0" 0.000115
data-collector_1  | [2019-10-28T12:44:41Z WARN  data_collector] Request did not pass validation. Error message: Reques
t body empty. Request body:
data-collector_1  |
data-collector_1  | [2019-10-28T12:44:41Z INFO  actix_web::middleware::logger] 172.20.0.1:39040 PostmanRuntime/7.18.0
data-collector_1  | [2019-10-28T12:44:41Z INFO  actix_web::middleware::logger] 172.20.0.1:39040 "POST / HTTP/1.1" 400
78 "-" "PostmanRuntime/7.18.0" 0.000091
```

**Pull request merged**
